#! /usr/bin/env sh

python3 copyh.py

swig -python -py3 -c++ scge.i
g++ -c -x c++ -fPIC scge_wrap.cxx -I/usr/include/python3.2 -I/usr/include/freetype2
g++ -shared scge_wrap.o -lscge -L. -o _scge.so

rm scge_wrap.cxx
rm scge_wrap.o
#rm scge.hpp

if [ ! -d ./scge ]; then
	mkdir ./scge
fi

mv scge.py ./scge/__init__.py
mv _scge.so ./scge/_scge.so

if [ -d ./scge/shared ]; then
	rm -r ./scge/shared
fi

cp -r ./shared ./scge/shared



sudo python3 setup.py install

