#!/bin/bash

python3 copyh.py

swig -python -py3 -c++ scge.i
g++ -c -x c++ -fPIC scge_wrap.cxx -I/usr/include/python3.3 -I/usr/include/freetype2
g++ -shared scge_wrap.o -lscge -L. -o _scge.so

mv scge.py scge/__init__.py
mv _scge.so scge/_scge.so

python3 setup.py build
sudo python3 setup.py install
